// list of categories users can filter by
const categories = [
    "Communication",
    "Music",
    "Art",
    "Technology",
    "Design",
    "Gaming",
    "Culinary",
    "Education",
    "Health",
    "Science",
    "Literature",
    "Sports",
    "Travel",
    "Fashion",
    "Film",
    "Theater",
    "Dance",
    "Photography",
    "Architecture",
    "History",
    "Psychology",
    "Sociology",
    "Economics",
    "Politics",
    "Environment",
    "Law",
    "Agriculture",
    "Astrophysics",
    "Chemistry",
    "Mathematics",
    "Engineering",
    "Medicine",
    "Entrepreneurship",
    "Marketing",
    "Philosophy",
    "Religion",
    "Anthropology",
    "Zoology",
    "Botany",
    "Geography",
    "Meteorology",
    "Oceanography",
    "Geology",
    "Paleontology",
    "Archaeology",
    "Genetics",
    "Neuroscience",
    "Biotechnology",
    "Veterinary",
    "Forestry",
    "Urban Planning",
    "Public Administration",
    "Nonprofits",
    "Human Rights",
    "International Relations",
    "Cultural Studies",
    "Media Studies",
    "Information Technology",
    "Cybersecurity",
    "Robotics",
    "Artificial Intelligence",
    "Data Science",
    "Virtual Reality",
    "Augmented Reality",
    "Esports",
    "Crafts",
    "DIY",
    "Cooking",
    "Baking",
    "Beverages",
    "Nutrition",
    "Fitness",
    "Wellness",
    "Mental Health",
    "Pediatrics",
    "Oncology",
    "Cardiology",
    "Dermatology",
    "Orthopedics",
    "Gynecology",
    "Dentistry",
    "Optometry",
    "Pharmacy",
    "Veterinary Medicine",
    "Public Health",
    "Epidemiology",
    "Biostatistics",
    "Toxicology",
    "Immunology",
    "Pathology",
    "Anesthesiology",
    "Radiology",
    "Surgery",
    "Neurosurgery",
    "Plastic Surgery",
    "Pediatric Surgery",
    "Cardiac Surgery",
    "Trauma Surgery",
    "Military",
    "Aviation",
    "Maritime",
    "Space Exploration",
    "Astrobiology",
    "Exoplanets",
    "Stellar Astrophysics",
    "Galactic Astronomy",
    "Cosmology",
    "Particle Physics",
    "Quantum Mechanics",
    "Theory of Relativity",
    "String Theory",
    "Fluid Dynamics",
    "Statistical Mechanics",
    "Thermodynamics",
    "Electromagnetism",
    "Acoustics",
    "Optics",
    "Nuclear Physics",
    "Materials Science",
    "Metallurgy",
    "Polymer Science",
    "Nanotechnology",
    "Forensic Science",
    "Criminology",
    "Jurisprudence",
    "Constitutional Law",
    "International Law",
    "Corporate Law",
    "Intellectual Property Law",
    "Environmental Law",
    "Family Law",
    "Civil Rights Law",
    "Criminal Law",
    "Tax Law",
    "Real Estate Law",
    "Immigration Law",
    "Labor Law",
    "Elder Law",
    "Education Law",
    "Health Law",
    "Bankruptcy Law",
    "Administrative Law",
    "Antitrust Law",
    "Sports Law",
    "Entertainment Law",
    "Maritime Law",
    "Aviation Law",
    "Space Law",
  ];
  
  export default categories;